export const crisisResources = [
  {
    type: 'crisis',
    locale: 'en',
    title: 'National Suicide Prevention Lifeline',
    description: 'Free, confidential support 24/7',
    content: JSON.stringify({
      phone: '988',
      alternatePhone: '1-800-273-8255',
      website: 'https://988lifeline.org',
      availability: '24/7',
      languages: ['English', 'Spanish'],
      instructions: 'Call or text 988 for immediate support',
    }),
    category: 'hotline',
    tags: ['suicide', 'crisis', 'immediate'],
    order: 1,
    isActive: true,
  },
  {
    type: 'crisis',
    locale: 'en',
    title: 'Crisis Text Line',
    description: 'Text-based crisis support',
    content: JSON.stringify({
      textNumber: '741741',
      keyword: 'HOME',
      website: 'https://www.crisistextline.org',
      availability: '24/7',
      instructions: 'Text HOME to 741741 to connect with a crisis counselor',
    }),
    category: 'hotline',
    tags: ['text', 'crisis', 'immediate'],
    order: 2,
    isActive: true,
  },
  {
    type: 'crisis',
    locale: 'en',
    title: 'Emergency Services',
    description: 'Immediate emergency assistance',
    content: JSON.stringify({
      phone: '911',
      instructions: 'Call 911 for immediate emergency assistance',
      when: 'Life-threatening emergencies only',
    }),
    category: 'emergency',
    tags: ['emergency', 'immediate'],
    order: 3,
    isActive: true,
  },
  // Spanish resources
  {
    type: 'crisis',
    locale: 'es',
    title: 'Línea Nacional de Prevención del Suicidio',
    description: 'Apoyo gratuito y confidencial 24/7',
    content: JSON.stringify({
      phone: '988',
      alternatePhone: '1-800-273-8255',
      website: 'https://988lifeline.org/es',
      availability: '24/7',
      languages: ['Español', 'English'],
      instructions: 'Llame o envíe un mensaje de texto al 988 para obtener apoyo inmediato',
    }),
    category: 'hotline',
    tags: ['suicidio', 'crisis', 'inmediato'],
    order: 1,
    isActive: true,
  },
  // Add French, etc.
];