@host = http://localhost:5005
@username = Lucas

### Post Create User
POST {{host}}/auth/signup
Content-Type: application/json

{
    "username": "Lucas12346",
    "email": "lucasalexander1132@gmail.com",
    "password": "Password1!"
}

### Post Signin User
POST {{host}}/auth/signin
Content-Type: application/json

{
    "username": "Lucas12346",
    "password": "Password1!"
}

### Post Signout User
POST {{host}}/auth/signout

### Get Specific User
GET {{host}}/auth/{{username}}

### Get User that doesn't exist
GET {{host}}/auth/{{username}}Hi

### Get Me
GET {{host}}/auth/me


### Post Entry
POST {{host}}/user/entries
Content-Type: application/json

{
    "eventTags": [
        {
            "id": "cmidn0mog0002ux9mk02oroox"
        },
        {
            "id": "cmidn0mox000wux9m6i830qko"
        },
        {
            "id": "cmidn0mog0004ux9m06natymu"
        },
        {
            "id": "cmidn0mog0006ux9mlr988plm"
        },
        {
            "id": "cmidn0moq000bux9meo0vi16b"
        },
        {
            "id": "cmidn0moq000dux9maknbfpgg"
        },
        {
            "id": "cmidn0moq000fux9m4ztfwdxt"
        },
        {
            "id": "cmidn0moq000hux9mr45yv7av"
        },
        {
            "id": "cmidn0moq000jux9myok9piq9"
        },
        {
            "id": "cmidn0moq000lux9msvnmali1"
        },
        {
            "id": "cmidn0moq000nux9m6foirzin"
        },
        {
            "id": "cmidn0moq000pux9mi50vws5v"
        },
        {
            "id": "cmidn0mox000sux9mo4l7551v"
        },
        {
            "id": "cmidn0mox000uux9msvqwndxt"
        },
        {
            "id": "cmidn0mox000yux9m1kqibli6"
        },
        {
            "id": "cmidn0mox0010ux9mazishads"
        },
        {
            "id": "cmidn0mox0012ux9mvhf4vdp3"
        }
    ],
    "intensity": {"intensityMethod": "color_slider", "intensityRating": "Frigid", "intensityValue": 100}
}

### Get Initial Entries
GET {{host}}/user/entries

### Get Entries
GET {{host}}/user/entries/?limit=1000

### Get Tags
GET {{host}}/user/tags

### Post Tag
POST {{host}}/user/tags
Content-Type: application/json

{
    "sectionId": "cmidn0mog0000ux9m4tyv5tlg",
    "category": "response",
    "color": "--color-Charcoal",
    "icon": "mask",
    "name": "Head"
}

### Get Sections
GET {{host}}/user/sections